@startuml erd
!include table.pu
skinparam linetype ortho

  Company ||--|{ Location
  Company ||--|{ Comment
  Worker ||--|{ Comment
  Worker ||--|{ Like
  Location ||-|{ Comment
  Location ||--|{ Like
  Worker_follow }|--|| Worker
  Company_follow }|--|| Worker
  Worker_follow }|--|| Company
  Company_follow }|--|| Company
  Chat_room }|-|| Company
  Chat_room }|-|| Worker
  Message }|-|| Chat_room

@enduml